language: clojure

jdk:
  - openjdk13

script:
  - lein test

after_success:
  - CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
