CREATE TABLE lessons (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  demo_video_link VARCHAR(1000) NOT NULL,
  screenshots VARCHAR(1000) ARRAY,
  price NUMERIC(18, 4) NOT NULL,
  created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
