CREATE TABLE dresses (
  id SERIAL PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  size SMALLINT NOT NULL CHECK (size > 0),
  pictures VARCHAR(1000) ARRAY,
  price NUMERIC(18, 4) NOT NULL,
  created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
