CREATE TABLE orders (
  session_id VARCHAR(200) NOT NULL PRIMARY KEY,
  product_type VARCHAR(50) NOT NULL,
  email VARCHAR(100),
  fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
  created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
