name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.986
      - uses: actions/checkout@v2
      - name: Run tests and generate coverage report
        run: clojure -M:test:cloverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
