# This is a basic workflow to help you get started with Actions

name: Deploy to VPS

# Controls when the action will run.
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        env:
          JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: JDBC_DATABASE_URL
          script: |
            cd tmpclj/education_api/
            git checkout master
            git reset --hard HEAD
            git pull
            bash --login -c 'lein migrate prod'
            bash --login -c 'lein clean'
            bash --login -c 'lein uberjar'
            cp target/education-api-standalone.jar /home/site/API/education-api-standalone.jar
            bash --login -c 'pm2 restart education-api'
